### ISSUE TITLE
Please include tshark and snmp in the image

### ISSUE THREAD

**Issue by Noname2244** [trisulnsm/docker#1]
Please include tshark and snmp in future builds

**Comment by trisulnsm** [comment]
Will do. Thanks for the suggestion.

**Comment by Ondjultomte** [comment]
Excellent 👍  ! How about adding support for bedfellas firehol level3 ?

**Comment by trisulnsm** [comment]
Hi ,

Here is some good news.

1. We just pushed a new docker image with tshark and snmp tools.

2. You can install the FireHOL App - that gives you Priority-1 alerts for FireHOL-Level1 and Priority-3 for Level3.  To install Trisul Apps. Login as admin and go to  Webadmin > Apps. 

cheers
