### ISSUE TITLE
Moved docker files and now experience database + web errors

### ISSUE THREAD

**Issue by npitsec** [trisulnsm/docker#2]
Hello,
The docker container was running successfully for months as part of a "test". I started a fresh new container and see the following errors on startup:

Thu Apr 12 15:04:42 2018.519109 ERROR Unable to DB.ApplyMigrations to file err=sqlite3_command::prepare([ALTER TABLE TRISUL_CTL_COUNTERVARS ADD COLUMN BottomNCount   INTEGER]) failed. Reason=[duplicate column name: BottomNCount]

Thu Apr 12 15:04:42 2018.526533 FATAL StatsEngineFactory:System: Migration needed, but failed to apply to /usr/local/var/lib/trisul-config/domain0/context0/profile0/TRISULCONFIG.SQDB

Thu Apr 12 15:04:42 2018.526582 FATAL StatsEngineFactory:System: Underlying error code = sqlite3_command::prepare([ALTER TABLE TRISUL_CTL_COUNTERVARS ADD COLUMN BottomNCount   INTEGER]) failed. Reason=[duplicate column name: BottomNCount]

Thu Apr 12 15:04:42 2018.526626 ERROR [CFGEXC][config0]FAILED to create bootstrap config db at /usr/local/var/lib/trisul-config/domain0/context0/profile0/TRISULCONFIG.SQDB

When I visit the webpage and login I see the following error: 
    You have not yet started theTrisulserver
    You just started Trisul less than 5 minutes ago.
    Trisul is listening on the wrong interface for traffic.
    You are looking at the wrong context

I have in fact deleted my "trisul6_root" folder and sub-content to start over along with a new container instance. But all of the above happens every single time.

When I start the container using the "second" tag, all works just fine. So I think something happened in a newer version that has broken the database.

**Comment by trisulnsm** [comment]
Have you tried starting the probe ? These errors may just be warnings and the data might still be captured.  Check the dashboards after about 5 minutes. 

If that still doesnt solve the problem, try  `docker pull` the latest image.  We just pushed a new image today that will not have this problem.  Also the new image has a ton of other improvements, so you may want to update anyway.

Thanks for reporting this ,
