### ISSUE TITLE
SNMP interface description truncation

### ISSUE THREAD

**Issue by Noname2244** [trisulnsm/docker#3]
When using SNMP to poll for interface description, the description is truncated after the first "space"

show int int 1 des (from the router)
Gives this description on the router:
CU;CUST;name [VRF cust-guest - EXPORT];SU;FX:shared 1G;v-cust-guest;s-wan

Gives this result in trisul:
"CU;CUST;name

![image](https://user-images.githubusercontent.com/34089487/39169829-89ba2eae-4799-11e8-989c-3d6a0acfee57.png)

**Comment by trisulnsm** [comment]
Currently the interface name is truncated at the first whitespace character. Is this what you are seeing?

**Comment by Noname2244** [comment]
Yes, it was, it's fixed in the two latest versions
