### ISSUE TITLE
Username & Password not working in Docker

### ISSUE THREAD

**Issue by arun81** [trisulnsm/docker#5]
Hi Team 

Good Day !!!!

Followed the Below Steps

sudo mkdir /opt/trisul6_root
sudo docker run  --net=host -v /opt/trisul6_root:/trisulroot -d trisulnsm/trisul6 --interface enp5s0 

Able to Login to http://IP:3000 but username and password admin / admin not working . What could be the issue 

![image](https://user-images.githubusercontent.com/13440263/51444127-78d31c80-1d19-11e9-8483-7d2857a51ad0.png)

Thanks

**Comment by trisulnsm** [comment]
Hi  Arun,

I tried it and it works as expected.

Note there is no 'slash' character

default username = admin
password = admin

Also can you do a docker pull, we pushed a major update last night.

**Comment by arun81** [comment]
Thanks a lot for your support and revert 
It works like a charm !!!!!

Thanks
